<a href="https://colab.research.google.com/github/dblanchfield/SpamNumber/blob/main/spamnumbercheck.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from bs4 import BeautifulSoup as bs
import pandas as pd
pd.set_option('display.max_colwidth', 500)
import time
import requests
import random
import re

In [7]:
#Create function to only allow numbers
def extract_int(x):
    return re.sub('[^\d]','', x)
#list of numbers


test_numbers = [extract_int(item) for item in input("Enter the phone numbers : ").split()]

t_numbers = [f'https://lookup.robokiller.com/search?q={i}' for i in test_numbers ]

# holders for name and data

names = []

data = []

#randomize request rate
rate = [i/10 for i in range(10)]

for tnum in t_numbers:

  #access page
  page = requests.get(tnum)

  #get content

  soup = bs(page.content)

  #add name and data
  names.extend([i.text for i in soup.find_all(class_='ts-label')])

  data.extend([i.text for i in soup.find_all(class_='ts-data')])

  #randomize request
  time.sleep(random.choice(rate))

Enter the phone numbers : a6306305050 8155060024

In [8]:
#create dataframe for scraped information

df = pd.DataFrame()

#store values in respective columns

df['Label'] = names

df['Value'] = data

df

                       Label              Value
0               Alternately:       +16306305050
1             Reported Name:
2         Reported Category:
3                 Last call:  February 11, 2021
4              Total Calls:                   1
5   Robokiller User Reports:                  0
6               Alternately:       +18155060024
7             Reported Name:
8         Reported Category:
9                 Last call:   October 14, 2020
10             Total Calls:                   1
11  Robokiller User Reports:                  0